import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ height: '100%' }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ minHeight: '100%', display: 'flex', flexDirection: 'column' }}
      >
        <Navbar />
        <div
          style={{
            width: '100%',
            paddingInline: '120px',
            display: 'flex',
            flexGrow: 1,
            minHeight: 0,
            paddingBottom: '40px',
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
